// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCuIii-lMEsfnrJmMgI0qzIE5TVd1NXA',
    appId: '1:359213301226:web:bb45fafb16b90b8ef6c693',
    messagingSenderId: '359213301226',
    projectId: 'wealthflow-ai-479620',
    authDomain: 'wealthflow-ai-479620.firebaseapp.com',
    storageBucket: 'wealthflow-ai-479620.firebasestorage.app',
    measurementId: 'G-V3FL3MQHP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZuT0CkFR7TDyQyyEvKM-14nlaoIwfNoY',
    appId: '1:359213301226:android:6ce0913fb9770090f6c693',
    messagingSenderId: '359213301226',
    projectId: 'wealthflow-ai-479620',
    storageBucket: 'wealthflow-ai-479620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGez3mV2ogslIOaSC5Q9voKRn4FHmxX5s',
    appId: '1:359213301226:ios:ad58ac11d1676288f6c693',
    messagingSenderId: '359213301226',
    projectId: 'wealthflow-ai-479620',
    storageBucket: 'wealthflow-ai-479620.firebasestorage.app',
    iosBundleId: 'com.example.mortgageSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGez3mV2ogslIOaSC5Q9voKRn4FHmxX5s',
    appId: '1:359213301226:ios:ad58ac11d1676288f6c693',
    messagingSenderId: '359213301226',
    projectId: 'wealthflow-ai-479620',
    storageBucket: 'wealthflow-ai-479620.firebasestorage.app',
    iosBundleId: 'com.example.mortgageSimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcCuIii-lMEsfnrJmMgI0qzIE5TVd1NXA',
    appId: '1:359213301226:web:4b426981304b7c75f6c693',
    messagingSenderId: '359213301226',
    projectId: 'wealthflow-ai-479620',
    authDomain: 'wealthflow-ai-479620.firebaseapp.com',
    storageBucket: 'wealthflow-ai-479620.firebasestorage.app',
    measurementId: 'G-437EF3E857',
  );
}
