import 'dart:io';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:quick_actions/quick_actions.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_vertexai/firebase_vertexai.dart';

// Firebase config (auto-generated by flutterfire)
import 'firebase_options.dart';

// --- SERVICE IMPORTS ---
import 'services/theme_service.dart';
import 'services/notification_service.dart';

// --- SCREEN IMPORTS ---
import 'screens/snapshot_screen.dart';
import 'screens/budget_management_screen.dart';
import 'screens/savings_management_screen.dart';
import 'screens/portfolio_rebalance_screen.dart';
import 'screens/debt_payoff_screen.dart';
import 'screens/history_screen.dart';
import 'screens/savings_growth_screen.dart';
import 'screens/eu_mortgage.dart';
import 'screens/uk_mortgage.dart';
import 'screens/rollover_tab.dart';
import 'screens/overpayment.dart';
import 'screens/refinance_screen.dart';
import 'screens/other_loan_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- FIREBASE INITIALIZATION ---
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("✅ Firebase Initialized Successfully");
  } catch (e) {
    print("❌ Firebase Initialization Failed: $e");
  }

  // --- VERTEX AI (Important) ---
  // No initialize() method exists. Instance is created automatically.
  try {
    FirebaseVertexAI.instanceFor(location: 'europe-west2');
    print("🤖 Vertex AI Ready (europe-west2)");
  } catch (e) {
    print("❌ Vertex AI Setup Error: $e");
  }

  // --- NOTIFICATIONS ---
  if (Platform.isAndroid || Platform.isIOS) {
    final notificationService = NotificationService();
    await notificationService.initialize();
    await notificationService.scheduleMonthlyReminder();
  }

  runApp(
    ChangeNotifierProvider(
      create: (_) => ThemeService(),
      child: const MortgageApp(),
    ),
  );
}

class MortgageApp extends StatefulWidget {
  const MortgageApp({Key? key}) : super(key: key);

  @override
  State<MortgageApp> createState() => _MortgageAppState();
}

class _MortgageAppState extends State<MortgageApp> {
  final GlobalKey<BudgetManagementScreenState> _budgetKey = GlobalKey();
  final _quickActions = const QuickActions();

  /// Bottom Navigation selected index (0–5)
  int _selectedIndex = 3;

  /// The real page currently displayed
  int _currentPageIndex = 9;

  // MAIN PAGES
  late final List<Widget> _pages = [
    BudgetManagementScreen(key: _budgetKey),   // 0
    const SavingsManagementScreen(),           // 1
    const PortfolioRebalanceScreen(),          // 2
    const EuMortgageScreen(),                  // 3
    const UkMortgageScreen(),                  // 4
    const RolloverTab(),                       // 5
    const OverpaymentScreen(),                 // 6
    const DebtPayoffScreen(),                  // 7
    const HistoryScreen(),                     // 8
    const SnapshotScreen(),                    // 9
    const RefinanceScreen(),                   // 10
    const SavingsGrowthScreen(),               // 11
    const OtherLoanScreen(),                   // 12
  ];

  final List<String> _pageTitles = const [
    'Budget Management',   // 0
    'Savings Management',  // 1
    'Portfolio AI',        // 2
    'EU Mortgage',         // 3
    'UK Mortgage',         // 4
    'Rollover',            // 5
    'Overpayment',         // 6
    'Debt Payoff',         // 7
    'History',             // 8
    'Snapshot',            // 9
    'Refinance Analysis',  // 10
    'Savings Growth',      // 11
    'Other Loan',          // 12
  ];

  /// Maps bottom bar buttons → actual page indexes
  final List<int> _bottomBarPageIndices = const [
    0,   // Budget
    1,   // Savings
    2,   // Portfolio AI
    9,   // Snapshot
    11,  // Growth
    8,   // History
  ];

  @override
  void initState() {
    super.initState();
    _setupQuickActions();
  }

  // QUICK ACTIONS (App Icon Long-Press Shortcuts)
  void _setupQuickActions() {
    if (Platform.isAndroid || Platform.isIOS) {
      _quickActions.initialize((shortcutType) {
        if (shortcutType == 'action_quick_add') {
          _jumpToPage(0); // Switch to Budget Page

          Future.delayed(const Duration(milliseconds: 500), () {
            _budgetKey.currentState?.showQuickAddDialog();
          });
        }
      });

      _quickActions.setShortcutItems(const [
        ShortcutItem(
          type: 'action_quick_add',
          localizedTitle: 'Quick Add',
          icon: 'flash_icon',
        ),
      ]);
    }
  }

  int _mapNavIndexToPage(int navIndex) {
    return _bottomBarPageIndices[navIndex];
  }

  int _mapPageToNavIndex(int pageIndex) {
    int navIndex = _bottomBarPageIndices.indexOf(pageIndex);
    return navIndex != -1 ? navIndex : 3; // Default to Snapshot
  }

  void _jumpToPage(int pageIndex) {
    setState(() {
      _currentPageIndex = pageIndex;
      _selectedIndex = _mapPageToNavIndex(pageIndex);
    });
  }

  Widget _buildDrawer() {
    final items = <_DrawerItem>[
      const _DrawerItem(index: 3, icon: Icons.euro, title: 'EU Mortgage'),
      const _DrawerItem(index: 4, icon: Icons.home, title: 'UK Mortgage'),
      const _DrawerItem(index: 5, icon: Icons.trending_up, title: 'Rollover'),
      const _DrawerItem(index: 6, icon: Icons.payments, title: 'Overpayment'),
      const _DrawerItem(index: 7, icon: Icons.bar_chart, title: 'Debt Payoff'),
      const _DrawerItem(index: 10, icon: Icons.swap_horizontal_circle, title: 'Refinance'),
      const _DrawerItem(index: 12, icon: Icons.credit_card, title: 'Other Loan'),
    ];

    return Drawer(
      child: ListView(
        padding: EdgeInsets.zero,
        children: [
          DrawerHeader(
            decoration: BoxDecoration(color: Theme.of(context).primaryColor),
            child: const Text('More Tools',
                style: TextStyle(color: Colors.white, fontSize: 24)),
          ),
          for (final item in items)
            Builder(
              builder: (context) => ListTile(
                leading: Icon(item.icon),
                title: Text(item.title),
                onTap: () {
                  Navigator.pop(context);
                  _jumpToPage(item.index);
                },
              ),
            ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeService>(
      builder: (context, themeService, _) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'WealthFlow',
          themeMode: themeService.mode,
          theme: ThemeData.light(useMaterial3: true),
          darkTheme: ThemeData.dark(useMaterial3: true),
          home: Scaffold(
            appBar: AppBar(
              title: Text(_pageTitles[_currentPageIndex]),
              backgroundColor: Theme.of(context).primaryColor,
              foregroundColor: Colors.white,
            ),

            drawer: _buildDrawer(),
            body: _pages[_currentPageIndex],

            bottomNavigationBar: NavigationBar(
              selectedIndex: _selectedIndex,
              onDestinationSelected: (index) {
                _jumpToPage(_mapNavIndexToPage(index));
              },
              destinations: const [
                NavigationDestination(
                  icon: Icon(Icons.account_balance_wallet_outlined),
                  selectedIcon: Icon(Icons.account_balance_wallet),
                  label: 'Budget',
                ),
                NavigationDestination(
                  icon: Icon(Icons.savings_outlined),
                  selectedIcon: Icon(Icons.savings),
                  label: 'Savings',
                ),
                NavigationDestination(
                  icon: Icon(Icons.query_stats),
                  selectedIcon: Icon(Icons.query_stats_outlined),
                  label: 'Invest',
                ),
                NavigationDestination(
                  icon: Icon(Icons.pie_chart_outline),
                  selectedIcon: Icon(Icons.pie_chart),
                  label: 'Snapshot',
                ),
                NavigationDestination(
                  icon: Icon(Icons.trending_up_outlined),
                  selectedIcon: Icon(Icons.trending_up),
                  label: 'Growth',
                ),
                NavigationDestination(
                  icon: Icon(Icons.history_outlined),
                  selectedIcon: Icon(Icons.history),
                  label: 'History',
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}

class _DrawerItem {
  final int index;
  final IconData icon;
  final String title;

  const _DrawerItem({
    required this.index,
    required this.icon,
    required this.title,
  });
}
